export enum EVENT_SORT {
  SORT_FREE_EVENTS = 'SORT_FREE_EVENTS',
  SORT_DATE_AT = 'SORT_DATE_AT',
  SORT_UP_PRICE = 'SORT_UP_PRICE',
  SORT_DOWN_PRICE = 'SORT_DOWN_PRICE',
  SORT_POPULAR = 'SORT_POPULAR',
  SORT_FOVORITES = 'SORT_FOVORITES',
}
