export const TEXT = {
  ALL_SERVICES: 'Все сервисы',
  ASSISTANT: 'Помощник',
  CATEGORIES: 'Категория',
  CITY: 'Город',
  COST_PARTICIPATION: 'Стоимость участия',
  CREATED: 'Созданные',
  DATE: 'Дата',
  DESCRIPTIONS: 'Описание',
  EMPTY: 'Пусто',
  EVENT: 'Мероприятие',
  EVENT_PUBLIC: 'Мероприятие опубликовано!',
  EVENT_SUCCESS_DESCRIPRION: 'Отменить участие вы можете в карточке мероприятия или в профиле в разделе “я иду...”',
  EVENTS: 'Мероприятия',
  EVENTS_EDIT: 'Редактор мероприятий',
  FREE: 'Бесплатно',
  GO: 'Поехали!',
  GO_EVENTS: 'Перейти к мероприятиям',
  GO_PROFILE: 'Перейти в профиль',
  GUIDES_AND_ARTICLES: 'Гайды и статьи',
  I_GO: 'Я иду',
  I_SEARCH: 'Я ищу...',
  HISTORY: 'История',
  LIDER_BOARD: 'Лидерборд',
  LINK_DISCUSSION: 'Сылка на обсуждение',
  LINK_GOOGLE_MAPS: 'Ссылка на googlemaps',
  LIST_USERS: 'Список участников',
  LOCATION: 'Местоположение',
  MARKET: 'Барахолка',
  MORE: 'Еще',
  NAME: 'Название',
  NOT_CATEGORY: 'Без категории',
  NOT_FOUND: 'Не найден',
  OPEN: 'Открыть',
  OUR_SERVICES: 'Наши сервисы',
  PARCIPATION_CONFIRMED: 'Участие подтверждено!',
  PAWS: 'Лапки',
  PLACEHOLDER_GOOGLE_MAP: 'https://www.google.ru/maps...',
  PLACEHOLDER_DISCUSSION: 'https://t.me/kotikgo_bot...',
  RENT_HOUSE: 'Аренда жилья',
  SAY_EVENTS: 'Расскажите о мероприятии',
  SELECT_FILE: 'Выберите файл',
  SATURDAY_CLEAN: 'Субботник на Çoban plaj',
  SEND: 'Отправить',
  SORT: 'Сортировка',
  TIME: 'Время',
  TRANSFERS: 'Трансферы',
  USEFUL_LINKS: 'Полезные ссылки',
  USER: 'Пользователь',
  VIEW_EVENTS: 'Просмотреть мероприятия',
  WHAT_PAWS: 'Что такое лапки?',
  YOU: 'Вы',
  YOU_CREDITED: 'Вам начислено',
}
