export const VARIABLES = {
  HOURS: 24,
  LOGO: 'KOTIK',
  LOGO_PREFIX: 'G',
  MINUTES: 59,

  REGISTER_FIELD_CATEGORY: 'category' as const,
  REGISTER_FIELD_CITY_ID: 'cityId' as const,
  REGISTER_FIELD_CURRENCY: 'currency' as const,
  REGISTER_FIELD_DATE: 'date' as const,
  REGISTER_FIELD_DATE_TIME: 'datetime' as const,
  REGISTER_FIELD_DESCRIPTION: 'description' as const,
  REGISTER_FIELD_HOUR: 'hour' as const,
  REGISTER_FIELD_IMAGE: 'image' as const,
  REGISTER_FIELD_LOCATION: 'location' as const,
  REGISTER_FIELD_MINUTE: 'minute' as const,
  REGISTER_FIELD_PRICE: 'price' as const,
  REGISTER_FIELD_SORT: 'sort' as const,
  REGISTER_FIELD_TILE: 'title' as const,
  REGISTER_FIELD_URL: 'url' as const,

  TABS_I_GO: 'iGo',
  TABS_CREATED: 'created',
  TABS_HISTORY: 'history',
  TABS_LIDER_BOARD: 'liderboard',
}
